
name: CMake
on: [push, pull_request]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
        - name: gcc-11
          compiler: g++-11
          packages: >
            g++-11
          compiler-flags: ""

        - name: clang-12-libstdc++
          compiler: clang++-12
          packages: >
            g++-11
            clang++-12
          compiler-flags: "-stdlib=libstdc++"


    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install Compilers
      run: |
        sudo apt-get install ${{ matrix.packages }}

    - name: Configure CMake
      working-directory: ${{ github.workspace }}
      run: >
        cmake
        -B build
        -DCMAKE_CXX_COMPILER=${{ matrix.compiler }}
        -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
        -DCMAKE_CXX_FLAGS="${{ matrix.compiler-flags }}"

    - name: Build
      working-directory: ${{ github.workspace }}
      # Build your program with the given configuration
      run: >
        cmake
        --build build
        --config ${{ env.BUILD_TYPE }}


    # TODO: create test programs in test/ directory, register these with CTest
    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{env.BUILD_TYPE}}
